/**
 * Created by zahmed on 16-Jan-15.
 *
 * Description:
 * - This script is responsible for exporting fulfillment to Magento store as Shipment
 * -
 * Referenced By:
 * -
 * Dependency:
 * - Script Parameters:
 *   -
 * -
 * - Script Id:
 *   - customscript_magento_item_sync_sch
 * -
 * - Deployment Id:
 *   - customdeploy_magento_item_sync_sch
 * -
 * - Scripts:
 *   - folio3ConnectorLicenseVerification.js
 *   - mc_sync_constants.js
 *   - f3_inventory_sync_script_dao.js
 *   - f3_utility_methods.js
 *   - f3mg_connector_constants.js
 *   - f3mg_connector_common.js
 *   - f3mg_xml_utility.js
 *   - f3_external_system_config_dao.js
 *   - f3_client_factory.js
 *   - f3mg_ns_mg_shipping_methods_map_dao.js
 */

var FulfillmentExportHelper = (function () {
    return {
        // userevent start: creating shipment in Magento
        setShipmentIdInFulfillment: function (shipmentId) {
            var rec = nlapiLoadRecord(nlapiGetRecordType(), nlapiGetRecordId(), null);
            rec.setFieldValue(ConnectorConstants.Transaction.Fields.MagentoId, shipmentId + '');
            rec.setFieldValue(ConnectorConstants.Transaction.Fields.MagentoStore, ConnectorConstants.CurrentStore.systemId);
            nlapiSubmitRecord(rec);
        },

        /**
         * Export Fulfillment
         * @param sessionID
         * @param magentoSO
         * @return {*|{status: boolean, faultCode: string, faultString: string, result: Array}}
         */
        syncFulfillmentMagento: function (sessionID, magentoSO) {
            var responseMagento;
            var magentoSOId = magentoSO.getFieldValue(ConnectorConstants.Transaction.Fields.MagentoId);
            var magentoItemIds = ConnectorCommon.getMagentoItemIds(ConnectorCommon.getFulfillmentItems());


            // create shipment in Magento
            responseMagento = ConnectorConstants.CurrentWrapper.createFulfillment(sessionID, magentoItemIds, magentoSOId);

            if (!responseMagento.status) {
                Utility.logDebug('Error', 'Export fulfillment record -- ID: ' + '--' + responseMagento.faultCode + '--' + responseMagento.faultString);
                return;
            }
            else {
                Utility.logDebug('set magento shipment id', 'Im Setting ID ' + responseMagento.result);
                //nlapiSetFieldValue(ConnectorConstants.Transaction.Fields.MagentoId, responseMagento.result);

                // Check for feature availability
                if (!FeatureVerification.isPermitted(Features.EXPORT_ITEM_FULFILLMENT_TRACKING_INFO, ConnectorConstants.CurrentStore.permissions)) {
                    Utility.logEmergency('FEATURE PERMISSION', Features.EXPORT_ITEM_FULFILLMENT_TRACKING_INFO + ' NOT ALLOWED');
                    return responseMagento;
                }

                var upsPackage = '';
                var totalPackages;
                // packages sublist is generated by carrier / netsuite feature
                if (nlapiGetLineItemCount('packageups') > 0) {
                    upsPackage = 'ups';
                }
                if (nlapiGetLineItemCount('packagefedex') > 0) {
                    upsPackage = 'fedex';
                }
                // from SO
                var carrier = magentoSO.getFieldValue('carrier');
                totalPackages = nlapiGetLineItemCount('package' + upsPackage);
                var carrierText = magentoSO.getFieldText('shipmethod');

                Utility.logDebug('carrier', carrier);
                Utility.logDebug('totalPackages', totalPackages);
                Utility.logDebug('carrierText', carrierText);

                var trackingNumbersIds = [];
                for (var p = 1; p <= totalPackages; p++) {
                    var tracking = nlapiGetLineItemValue('package' + upsPackage, 'packagetrackingnumber' + upsPackage, p);
                    if (!Utility.isBlankOrNull(tracking)) {
                        var responseTracking =
                            ConnectorConstants.CurrentWrapper.createTracking(responseMagento.result, carrier, carrierText, tracking, sessionID, magentoSOId);

                        Utility.logDebug('CHECK', 'I tried setting shipment tracking id Got this in response : ' + responseTracking.result);
                        trackingNumbersIds.push(responseTracking.result);
                    }
                }
                // update tracking ids for future modification in tracking numbers - it is a rare case
                responseMagento.trackingNumbersIdsStr = trackingNumbersIds.join(",");
            }

            return responseMagento;
        }
    };
})();

/**
 * FulfillmentExport class that has the actual functionality of userevent script.
 * All business logic will be encapsulated in this class.
 */
var FulfillmentExport = (function () {
    return {
        /**
         * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
         * @appliedtorecord recordType
         *
         * @param {String} type Operation types: create, edit, view, copy, print, email
         * @param {nlobjForm} form Current form
         * @param {nlobjRequest} request Request object
         * @returns {Void}
         */
        userEventBeforeLoad: function (type, form, request) {
            //TODO: Write Your code here
        },
        /**
         * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
         * @appliedtorecord recordType
         *
         * @param {String} type Operation types: create, edit, delete, xedit
         *                      approve, reject, cancel (SO, ER, Time Bill, PO & RMA only)
         *                      pack, ship (IF)
         *                      markcomplete (Call, Task)
         *                      reassign (Case)
         *                      editforecast (Opp, Estimate)
         * @returns {Void}
         */
        userEventBeforeSubmit: function (type) {
            //TODO: Write Your code here
        },

        /**
         * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
         * @appliedtorecord recordType
         *
         * @param {String} type Operation types: create, edit, delete, xedit,
         *                      approve, cancel, reject (SO, ER, Time Bill, PO & RMA only)
         *                      pack, ship (IF only)
         *                      dropship, specialorder, orderitems (PO only)
         *                      paybills (vendor payments)
         * @returns {Void}
         */
        userEventAfterSubmit: function (type) {
            try {

                // checking license validation
                if (!MC_SYNC_CONSTANTS.isValidLicense()) {
                    Utility.logDebug('Validate', 'License has expired');
                    return;
                }

                // only executes code when license is valid and type is create
                if (type.toString() === 'create') {

                    var orderId = nlapiGetFieldValue('orderid');
                    var recType = ConnectorCommon.getRecordTypeOfTransaction(orderId);

                    // if fulfillment is not creating from sales order then terminate
                    if (recType.toString() !== 'salesorder') {
                        return;
                    }

                    var magentoSO = nlapiLoadRecord('salesorder', orderId, null);
                    var salesOrderStore = magentoSO.getFieldValue(ConnectorConstants.Transaction.Fields.MagentoStore);
                    var salesOrderMagentoId = magentoSO.getFieldValue(ConnectorConstants.Transaction.Fields.MagentoId);

                    // if not sales order is not synced with magento then terminate
                    if (Utility.isBlankOrNull(salesOrderStore) || Utility.isBlankOrNull(salesOrderMagentoId)) {
                        return;
                    }

                    ConnectorConstants.initialize();
                    // getting configuration
                    var externalSystemConfig = ConnectorConstants.ExternalSystemConfig;
                    var sessionID;

                    var store = externalSystemConfig[salesOrderStore];
                    ConnectorConstants.CurrentStore = store;

                    // Check for feature availability
                    if (!FeatureVerification.isPermitted(Features.EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM, ConnectorConstants.CurrentStore.permissions)) {
                        Utility.logEmergency('FEATURE PERMISSION', Features.EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM + ' NOT ALLOWED');
                        return;
                    }

                    ConnectorConstants.CurrentWrapper = F3WrapperFactory.getWrapper(store.systemType);
                    ConnectorConstants.CurrentWrapper.initialize(store);
                    sessionID = ConnectorConstants.CurrentWrapper.getSessionIDFromServer(store.userName, store.password);

                    // if session id is not captured then terminate
                    if (Utility.isBlankOrNull(sessionID)) {
                        Utility.logDebug('sessionID', 'sessionID is empty');
                        return;
                    }

                    var response = FulfillmentExportHelper.syncFulfillmentMagento(sessionID, magentoSO);

                    if (response) {
                        FulfillmentExportHelper.setShipmentIdInFulfillment(response.result);
                    }

                }
            } catch (e) {
                Utility.logException('startup - afterSubmit', e);
            }
        }
    };
})();

/**
 * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
 * @appliedtorecord recordType
 *
 * @param {String} type Operation types: create, edit, view, copy, print, email
 * @param {nlobjForm} form Current form
 * @param {nlobjRequest} request Request object
 * @returns {Void}
 */
function FulfillmentExportBeforeLoad(type, form, request) {
    return FulfillmentExport.userEventBeforeLoad(type, form, request);
}

/**
 * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
 * @appliedtorecord recordType
 *
 * @param {String} type Operation types: create, edit, delete, xedit
 *                      approve, reject, cancel (SO, ER, Time Bill, PO & RMA only)
 *                      pack, ship (IF)
 *                      markcomplete (Call, Task)
 *                      reassign (Case)
 *                      editforecast (Opp, Estimate)
 * @returns {Void}
 */
function FulfillmentExportBeforeSubmit(type) {
    return FulfillmentExport.userEventBeforeSubmit(type);
}

/**
 * The recordType (internal id) corresponds to the "Applied To" record in your script deployment.
 * @appliedtorecord recordType
 *
 * @param {String} type Operation types: create, edit, delete, xedit,
 *                      approve, cancel, reject (SO, ER, Time Bill, PO & RMA only)
 *                      pack, ship (IF only)
 *                      dropship, specialorder, orderitems (PO only)
 *                      paybills (vendor payments)
 * @returns {Void}
 */
function FulfillmentExportAfterSubmit(type) {
    return FulfillmentExport.userEventAfterSubmit(type);
}
