/**
 * Created by zahmed on 14-Oct-14.
 */

var site = site || {};

site.godDivaCategories = [
    {"value": "-101", "text": "Home", "magValue": "46", "magText": "Clothing"},
    {"value": "-107", "text": "Home", "magValue": "46", "magText": "Clothing"},
    {"value": "62", "text": "Home : Accessories", "magValue": "82", "magText": ""},
    {"value": "166106", "text": "Home : Accessories : Belts", "magValue": "288", "magText": ""},
    {"value": "166101", "text": "Home : Accessories : Bracelets", "magValue": "283", "magText": ""},
    {"value": "166098", "text": "Home : Accessories : Clutch Bags", "magValue": "281", "magText": ""},
    {"value": "168795", "text": "Home : Accessories : Collars", "magValue": "287", "magText": ""},
    {"value": "166102", "text": "Home : Accessories : Earrings", "magValue": "284", "magText": ""},
    {"value": "166103", "text": "Home : Accessories : Necklaces", "magValue": "285", "magText": ""},
    {"value": "166104", "text": "Home : Accessories : Rings", "magValue": "286", "magText": ""},
    {"value": "166100", "text": "Home : Accessories : Shoulder Bags", "magValue": "282", "magText": ""},
    {"value": "168053", "text": "Home : Bottoms", "magValue": "45", "magText": ""},
    {"value": "166112", "text": "Home : Bottoms : Jeans", "magValue": "277", "magText": ""},
    {"value": "166092", "text": "Home : Bottoms : Maxi Skirts", "magValue": "274", "magText": ""},
    {"value": "166088", "text": "Home : Bottoms : Midi & Mixi Skirts", "magValue": "273", "magText": ""},
    {"value": "166086", "text": "Home : Bottoms : Mini Skirts", "magValue": "272", "magText": ""},
    {"value": "166108", "text": "Home : Bottoms : Pencil Skirts", "magValue": "275", "magText": ""},
    {"value": "167512", "text": "Home : Bottoms : Tights", "magValue": "276", "magText": ""},
    {"value": "29414", "text": "Home : Bottoms : Trousers", "magValue": "278", "magText": ""},
    {"value": "21", "text": "Home : Celebrity Style", "magValue": "85", "magText": "Shop by category"},
    {"value": "120", "text": "Home : Celebrity Style : Cheryl Cole", "magValue": "245", "magText": ""},
    {"value": "36888", "text": "Home : Celebrity Style : Eva Mendez", "magValue": "249", "magText": ""},
    {"value": "36895", "text": "Home : Celebrity Style : Kim Kardashian", "magValue": "255", "magText": ""},
    {"value": "108", "text": "Home : Celebrity Style : Kimberley Walsh", "magValue": "256", "magText": ""},
    {"value": "166362", "text": "Home : Celebrity Style : Kristen Stewart", "magValue": "257", "magText": ""},
    {"value": "36900", "text": "Home : Celebrity Style : Mila Kunis", "magValue": "260", "magText": ""},
    {"value": "219353", "text": "Home : Celebrity Style : Miranda Kerr", "magValue": "261", "magText": ""},
    {"value": "174805", "text": "Home : Collection", "magValue": "87", "magText": "Shop by collection"},
    {"value": "103012", "text": "Home : Collection : Goddiva Luxe Range", "magValue": "237", "magText": "Goddiva luxe"},
    {"value": "251639", "text": "Home : Collection : Hot Check Collection", "magValue": "239", "magText": "Hot check"},
    {"value": "212796", "text": "Home : Collection : Lace Collection", "magValue": "242", "magText": ""},
    {"value": "251965", "text": "Home : Collection : New Neutrals", "magValue": "240", "magText": ""},
    {"value": "239333", "text": "Home : Collection : Style Steals", "magValue": "296", "magText": ""},
    {"value": "251963", "text": "Home : Collection : Winter Florals", "magValue": "241", "magText": ""},
    {"value": "222483", "text": "Home : Collection : Workwear Dresses", "magValue": "243", "magText": "Workwear boutique"},
    {"value": "102469", "text": "Home : Deal", "magValue": "76", "magText": "Offers"},
    {"value": "250529", "text": "Home : Deal : Deal of the Week", "magValue": "297", "magText": ""},
    {"value": "174688", "text": "Home : Dresses", "magValue": "47", "magText": ""},
    {"value": "58207", "text": "Home : Dresses : Bodycon Dresses", "magValue": "234", "magText": ""},
    {"value": "56", "text": "Home : Dresses : Casual Dresses", "magValue": "230", "magText": ""},
    {"value": "123", "text": "Home : Dresses : Celebrity Dresses", "magValue": "229", "magText": ""},
    {"value": "165203", "text": "Home : Dresses : Cocktail Dresses", "magValue": "228", "magText": ""},
    {"value": "54", "text": "Home : Dresses : Evening Dresses", "magValue": "226", "magText": ""},
    {"value": "27512", "text": "Home : Dresses : Little Black Dress", "magValue": "235", "magText": ""},
    {"value": "55", "text": "Home : Dresses : Maxi Dresses", "magValue": "227", "magText": ""},
    {"value": "165208", "text": "Home : Dresses : Midi & Mixi Dresses", "magValue": "231", "magText": ""},
    {"value": "165207", "text": "Home : Dresses : Mini Dresses", "magValue": "232", "magText": ""},
    {"value": "53", "text": "Home : Dresses : Party Dresses", "magValue": "225", "magText": ""},
    {"value": "16886", "text": "Home : Dresses : Prom Dresses", "magValue": "233", "magText": ""},
    {"value": "257933", "text": "Home : Dresses : Sequin Dresses", "magValue": "222", "magText": ""},
    {"value": "57", "text": "Home : Dresses : Summer Dresses", "magValue": "236", "magText": ""},
    {"value": "10207", "text": "Home : Hottest Dress Trends : Knitwear", "magValue": "51", "magText": ""},
    {"value": "256538", "text": "Home : jewel tones bold color dress", "magValue": "238", "magText": "jewel tones"},
    {"value": "9366", "text": "Home : New In", "magValue": "80", "magText": "What's New"},
    {"value": "174791", "text": "Home : Outerwear", "magValue": "43", "magText": ""},
    {"value": "253690", "text": "Home : Outerwear : coats", "magValue": "280", "magText": ""},
    {"value": "58", "text": "Home : Outerwear : Jackets", "magValue": "279", "magText": ""},
    {"value": "9728", "text": "Home : Shoes", "magValue": "81", "magText": ""},
    {"value": "166093", "text": "Home : Shoes : Boots", "magValue": "290", "magText": ""},
    {"value": "166094", "text": "Home : Shoes : Flats", "magValue": "291", "magText": ""},
    {"value": "166096", "text": "Home : Shoes : High-Heels", "magValue": "293", "magText": ""},
    {"value": "166095", "text": "Home : Shoes : Mid Heels", "magValue": "292", "magText": ""},
    {"value": "59", "text": "Home : Tops", "magValue": "53", "magText": ""},
    {"value": "165226", "text": "Home : Tops : Blouses", "magValue": "109", "magText": ""},
    {"value": "165229", "text": "Home : Tops : Cardigans", "magValue": "268", "magText": ""},
    {"value": "165217", "text": "Home : Tops : Crop Tops & Bralets", "magValue": "105", "magText": ""},
    {"value": "165228", "text": "Home : Tops : Jumpers", "magValue": "267", "magText": ""},
    {"value": "165337", "text": "Home : Tops : Kimonos", "magValue": "269", "magText": ""},
    {"value": "165218", "text": "Home : Tops : Shirts", "magValue": "106", "magText": ""},
    {"value": "165219", "text": "Home : Tops : T-shirts", "magValue": "108", "magText": ""},
    {"value": "165220", "text": "Home : Tops : Tunics", "magValue": "107", "magText": ""},
    {"value": "165213", "text": "Home : Tops : Vest & Camisoles", "magValue": "101", "magText": ""},

    {"value": "9729", "text": "Home : Bags", "magValue": "", "magText": ""},
    {"value": "250533", "text": "Home : Bloggers Inspired Styles", "magValue": "", "magText": ""},
    {"value": "27479", "text": "Home : Bottoms : Leggings", "magValue": "", "magText": ""},
    {"value": "59299", "text": "Home : Bottoms : Party Dresses Test", "magValue": "", "magText": ""},
    {"value": "166114", "text": "Home : Bottoms : Shorts", "magValue": "", "magText": ""},
    {"value": "250532", "text": "Home : Catwalk Inspired Styles", "magValue": "", "magText": ""},
    {"value": "36776", "text": "Home : Celebrity Style : Alexa Chung", "magValue": "", "magText": ""},
    {"value": "142951", "text": "Home : Celebrity Style : Amy Childs", "magValue": "", "magText": ""},
    {"value": "58361", "text": "Home : Celebrity Style : Camilla Alves", "magValue": "", "magText": ""},
    {"value": "162258", "text": "Home : Celebrity Style : Cara Delevigne", "magValue": "", "magText": ""},
    {"value": "36885", "text": "Home : Celebrity Style : Christina Ricci", "magValue": "", "magText": ""},
    {"value": "222452", "text": "Home : Celebrity Style : Dannii Minogue", "magValue": "", "magText": ""},
    {"value": "116", "text": "Home : Celebrity Style : Duffy", "magValue": "", "magText": ""},
    {"value": "36887", "text": "Home : Celebrity Style : Emma Watson", "magValue": "", "magText": ""},
    {"value": "69111", "text": "Home : Celebrity Style : Jennifer Lopez", "magValue": "253", "magText": ""},
    {"value": "113", "text": "Home : Celebrity Style : Jessica Alba", "magValue": "251", "magText": ""},
    {"value": "28457", "text": "Home : Celebrity Style : Fearne Cotton", "magValue": "", "magText": ""},
    {"value": "105", "text": "Home : Celebrity Style : Heidi Klum", "magValue": "", "magText": ""},
    {"value": "36893", "text": "Home : Celebrity Style : Jameela Jamil", "magValue": "", "magText": ""},
    {"value": "119", "text": "Home : Celebrity Style : Kate Middleton", "magValue": "", "magText": ""},
    {"value": "97387", "text": "Home : Celebrity Style : Kate Moss", "magValue": "", "magText": ""},
    {"value": "114", "text": "Home : Celebrity Style : Kelly Brook", "magValue": "", "magText": ""},
    {"value": "111", "text": "Home : Celebrity Style : Katy Perry", "magValue": "254", "magText": ""},
    {"value": "219352", "text": "Home : Celebrity Style : Mollie King", "magValue": "", "magText": ""},
    {"value": "36901", "text": "Home : Celebrity Style : Myleene Klass", "magValue": "", "magText": ""},
    {"value": "117559", "text": "Home : Celebrity Style : Nicole Scherzinger", "magValue": "", "magText": ""},
    {"value": "165202", "text": "Home : Celebrity Style : Rihanna", "magValue": "", "magText": ""},
    {"value": "223894", "text": "Home : Celebrity Style : Rita Ora", "magValue": "", "magText": ""},
    {"value": "216486", "text": "Home : Celebrity Style : Selena Gomez", "magValue": "", "magText": ""},
    {"value": "119567", "text": "Home : Celebrity Style : Taylor Swift", "magValue": "", "magText": ""},
    {"value": "36910", "text": "Home : Celebrity Style : Tulisa of N-Dubz", "magValue": "", "magText": ""},
    {"value": "6", "text": "Home : Celebrity Style : Victoria Beckham", "magValue": "", "magText": ""},
    {"value": "130354", "text": "Home : Cheap Dresses", "magValue": "", "magText": ""},
    {"value": "251635", "text": "Home : Collection : Autumn Winter 2014/2015", "magValue": "", "magText": ""},
    {"value": "240227", "text": "Home : Collection : Cute Co-ordinates", "magValue": "", "magText": ""},
    {"value": "238027", "text": "Home : Collection : Eastern Influence", "magValue": "", "magText": ""},
    {"value": "184624", "text": "Home : Collection : Festival Fashion", "magValue": "", "magText": ""},
    {"value": "192914", "text": "Home : Collection : Goddiva Denim", "magValue": "", "magText": ""},
    {"value": "108453", "text": "Home : Collection : Goddiva Sport", "magValue": "", "magText": ""},
    {"value": "244842", "text": "Home : Collection : Hawaii", "magValue": "", "magText": ""},
    {"value": "177841", "text": "Home : Collection : Holiday Shop", "magValue": "", "magText": ""},
    {"value": "210106", "text": "Home : Collection : Limited Edition", "magValue": "", "magText": ""},
    {"value": "158875", "text": "Home : Collection : Monochrome", "magValue": "", "magText": ""},
    {"value": "29424", "text": "Home : Collection : Plus Size", "magValue": "", "magText": ""},
    {"value": "237909", "text": "Home : Collection : Pop Art", "magValue": "", "magText": ""},
    {"value": "208877", "text": "Home : Collection : Rebel", "magValue": "", "magText": ""},
    {"value": "215136", "text": "Home : Collection : Seasonal Opulence", "magValue": "", "magText": ""},
    {"value": "232428", "text": "Home : Collection : Spring Pastels", "magValue": "", "magText": ""},
    {"value": "174124", "text": "Home : Collection : Summer Florals", "magValue": "", "magText": ""},
    {"value": "226272", "text": "Home : Collection : summer stock", "magValue": "", "magText": ""},
    {"value": "175809", "text": "Home : Collection : Swimwear", "magValue": "", "magText": ""},
    {"value": "27919", "text": "Home : Collection : Winter Wardrobe", "magValue": "", "magText": ""},
    {"value": "251962", "text": "Home : Collection : Winter Wardrobe a", "magValue": "", "magText": ""},
    {"value": "257970", "text": "Home : Deal : gift a friend", "magValue": "", "magText": ""},
    {"value": "251499", "text": "Home : Deal : Mighty Deals", "magValue": "", "magText": ""},
    {"value": "165209", "text": "Home : Dresses : Bandeau Dresses", "magValue": "", "magText": ""},
    {"value": "246898", "text": "Home : Dresses : Beaded Dresses", "magValue": "", "magText": ""},
    {"value": "165205", "text": "Home : Dresses : Flapper Dresses", "magValue": "", "magText": ""},
    {"value": "165212", "text": "Home : Dresses : Knitted Dresses", "magValue": "", "magText": ""},
    {"value": "244836", "text": "Home : Dresses : Locayta Dresses", "magValue": "", "magText": ""},
    {"value": "248051", "text": "Home : Dresses : Multi Tie", "magValue": "", "magText": ""},
    {"value": "27483", "text": "Home : Dresses : One Shoulder Dress", "magValue": "", "magText": ""},
    {"value": "165206", "text": "Home : Dresses : Peplum Dresses", "magValue": "", "magText": ""},
    {"value": "165211", "text": "Home : Dresses : Shift Dresses", "magValue": "", "magText": ""},
    {"value": "80250", "text": "Home : Dresses : Skater Dresses", "magValue": "", "magText": ""},
    {"value": "9275", "text": "Home : Hottest Dress Trends", "magValue": "", "magText": ""},
    {"value": "27478", "text": "Home : JumpSuits", "magValue": "", "magText": ""},
    {"value": "166119", "text": "Home : Playsuits", "magValue": "", "magText": ""},
    {"value": "2163", "text": "Home : Press", "magValue": "", "magText": ""},
    {"value": "247682", "text": "Home : Sale", "magValue": "", "magText": ""},
    {"value": "256537", "text": "Home : Sale : crazy sale - myvouchercodes £1", "magValue": "", "magText": ""},
    {"value": "247687", "text": "Home : Sale : sale Accessories", "magValue": "", "magText": ""},
    {"value": "247683", "text": "Home : Sale : sale Bottoms", "magValue": "", "magText": ""},
    {"value": "247684", "text": "Home : Sale : sale Dresses", "magValue": "", "magText": ""},
    {"value": "247685", "text": "Home : Sale : sale Jumpsuits & Playsuits.", "magValue": "", "magText": ""},
    {"value": "247688", "text": "Home : Sale : sale Knitwear", "magValue": "", "magText": ""},
    {"value": "247691", "text": "Home : Sale : sale Shoes", "magValue": "", "magText": ""},
    {"value": "247690", "text": "Home : Sale : sale Sportswear", "magValue": "", "magText": ""},
    {"value": "247689", "text": "Home : Sale : sale Swimwear", "magValue": "", "magText": ""},
    {"value": "247686", "text": "Home : Sale : sale Tops", "magValue": "", "magText": ""},
    {"value": "250535", "text": "Home : Sale : sale £14.99", "magValue": "", "magText": ""},
    {"value": "247692", "text": "Home : Sale : sale £19", "magValue": "", "magText": ""},
    {"value": "250536", "text": "Home : Sale : sale £4.99", "magValue": "", "magText": ""},
    {"value": "223687", "text": "Home : Sale : sale £9.99", "magValue": "", "magText": ""},
    {"value": "61", "text": "Home : Skirts", "magValue": "", "magText": ""},
    {"value": "250534", "text": "Home : Styles Loved by Press", "magValue": "", "magText": ""},
    {"value": "26781", "text": "Home : TV-Campaign", "magValue": "", "magText": ""}
];


site.size = {
    '2': '280',
    '3': '279',
    '4': '278',
    '5': '277',
    '6': '256',
    '7': '276',
    '8': '257',
    '10': '258',
    '12': '259',
    '14': '260',
    '16': '261',
    '18': '262',
    '20': '263',
    '22': '264',
    '24': '265',
    '25': '275',
    '26': '274',
    '27': '273',
    '28': '272',
    '29': '271',
    '30': '270',
    '31': '269',
    '32': '268',
    'XS': '249',
    'S': '250',
    'M': '251',
    'L': '252',
    'XL': '253',
    'SM': '254',
    'ML': '255',
    'XXL': '267',
    'One Size': '266'
};

site.color = {
    "Animalmulti": "289",
    "Animalprint": "288",
    "Aqua": "287",
    "Aquamulti": "286",
    "Armygreen": "285",
    "Babypink": "299",
    "Beige": "298",
    "Berry": "297",
    "Black": "282",
    "Blackblack": "296",
    "Blackblue": "295",
    "Blackcream": "294",
    "Blackgold": "293",
    "Blackgreen": "292",
    "Blackgunmetal": "291",
    "Blackprint": "290",
    "Blackred": "311",
    "Blacksilver": "310",
    "Blackwhite": "309",
    "Blue": "308",
    "Blueblack": "307",
    "Bluedipdye": "306",
    "Bluefloral": "305",
    "Bluegold": "304",
    "Bluemulti": "209",
    "Blush": "303",
    "Bronze": "302",
    "Brown": "283",
    "Burgundy": "301",
    "Burntorange": "300",
    "Camel": "281",
    "Cerise": "368",
    "Ceriseblack": "322",
    "Cerisemulti": "321",
    "Ceriseprint": "320",
    "Champagne": "319",
    "Charcoal": "318",
    "Chocolate": "317",
    "Cobalt": "316",
    "Cobaltblue": "315",
    "Copper": "314",
    "Coral": "313",
    "Cowprint": "312",
    "Cream": "284",
    "Creamblack": "338",
    "Creamprint": "203",
    "Darkgrey": "199",
    "Darkpurple": "198",
    "Darkred": "200",
    "Darksilver": "197",
    "Dazzlingblue": "196",
    "Denim": "195",
    "Denimblue": "194",
    "Duskypink": "193",
    "Ecru": "192",
    "Emerald": "191",
    "Featherprint": "190",
    "Flamingo": "189",
    "Floral": "188",
    "Flowerprint": "187",
    "Fuchsia": "328",
    "Gold": "185",
    "Goldolive": "327",
    "Goldorange": "326",
    "Green": "182",
    "Greenmulti": "181",
    "Grey": "180",
    "Greyfloral": "179",
    "Greyyellow": "178",
    "Gunmetal": "177",
    "Heartprint": "176",
    "Hotpink": "173",
    "Ivory": "172",
    "Jade": "171",
    "Jadeprint": "170",
    "Jungleprint": "169",
    "Kaleidoscopeprint": "168",
    "Khaki": "166",
    "Lavender": "164",
    "Lemon": "163",
    "Leopardprint": "162",
    "Lightblue": "161",
    "Lilac": "156",
    "Lilacfloral": "155",
    "Lime": "154",
    "Limestripe": "103",
    "Magenta": "205",
    "Maroon": "206",
    "Midnightblue": "207",
    "Mint": "208",
    "Mixcolour": "210",
    "Mocha": "211",
    "Monochrome": "212",
    "Multicolour": "213",
    "Multiprint": "214",
    "Mustard": "215",
    "Navy": "216",
    "Navyprint": "217",
    "Neonblue": "218",
    "Neongreen": "219",
    "Neonorange": "220",
    "Neonpink": "221",
    "Nude": "222",
    "Orange": "224",
    "Orangeprint": "225",
    "Oyster": "226",
    "Peach": "230",
    "Pearl": "232",
    "Penguinprint": "233",
    "Pink": "235",
    "Pinkfloral": "236",
    "Plum": "237",
    "Print": "240",
    "Purple": "241",
    "Purpleprint": "242",
    "Rainbowprint": "243",
    "Red": "153",
    "Red Print": "152",
    "Redfloral": "150",
    "Redorange": "149",
    "Redprint": "148",
    "Royal Blue": "146",
    "royalblue": "369",
    "Royalprint": "145",
    "Rust": "143",
    "Sand": "140",
    "Scubablue": "139",
    "Silver": "138",
    "Silverivory": "346",
    "Silverolive": "345",
    "Snakeprint": "344",
    "Softkhaki": "343",
    "Stone": "134",
    "Sunnyforest": "133",
    "Tan": "132",
    "Tangerine": "131",
    "Taupe": "130",
    "Teal": "129",
    "Tribalprint": "126",
    "turquoise": "125",
    "Turquoise": "124",
    "Wedgewoodblue": "121",
    "White": "120",
    "Wine": "119",
    "Yellow": "244",
    "Yellowgreen": "246",
    "Zebraprint": "248"
};

/*
 site.size = {
 'S': '13',
 'M': '14',
 'L': '11',
 '3': '18',
 '4': '19',
 '5': '20',
 '6': '21',
 '7': '22',
 '8': '23'
 };
 site.color = {
 'Black': '6',
 'Cream': '12',
 'Blackred': '24'
 };
 */